# Generated by Django 6.0.5 on 2026-05-26 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobopening_jd_fields'),
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='candidate_email',
            field=models.EmailField(blank=True, help_text='Candidate email for interview notifications', max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlisted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_candidates', to='jobs.jobopening')),
                ('screening_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist', to='recruitment.screeningresult')),
                ('shortlisted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shortlisted_candidates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=10)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom/Meet link for online interviews', null=True)),
                ('venue', models.CharField(blank=True, help_text='Venue address for offline interviews', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_interviews', to=settings.AUTH_USER_MODEL)),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL)),
                ('shortlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.shortlist')),
            ],
        ),
    ]
