# Generated by Django 6.0.5 on 2026-06-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_resume_candidate_email_shortlist_interviewschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='pipeline_stage',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SHORTLISTED', 'Shortlisted'), ('ROUND_1', 'Round 1'), ('ROUND_2', 'Round 2'), ('ROUND_3', 'Round 3'), ('ROUND_4', 'Round 4'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='SHORTLISTED', max_length=20),
        ),
    ]
