# Generated by Django 6.0.5 on 2026-06-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_shortlist_pipeline_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlist',
            name='pipeline_stage',
        ),
    ]
