# Generated by Django 6.0.5 on 2026-06-02 10:35

from django.db import migrations, models

def fix_legacy_filenames(apps, schema_editor):
    """
    This function ensures that legacy data (which currently has 'legacy_upload'
    as the filename) becomes unique to satisfy the new unique_together constraint.
    """
    ScreeningResult = apps.get_model('recruitment', 'ScreeningResult')
    # Loop through all rows that currently have the default filename
    for result in ScreeningResult.objects.filter(source_filename='legacy_upload'):
        # Append the ID to make it unique (e.g., 'legacy_upload_1', 'legacy_upload_2')
        result.source_filename = f'legacy_upload_{result.id}'
        result.save(update_fields=['source_filename'])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobopening_jd_fields'),
        ('recruitment', '0004_remove_shortlist_pipeline_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresult',
            name='candidate_email',
            field=models.EmailField(blank=True, help_text='Auto-extracted from resume file', null=True),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='source_filename',
            field=models.CharField(default='legacy_upload', help_text='Filename inside MEDIA_ROOT/resumes/', max_length=255),
            preserve_default=False,
        ),
        # --- NEW: Run this function to fix duplicate filenames before applying the constraint ---
        migrations.RunPython(fix_legacy_filenames, migrations.RunPython.noop),
        # ---------------------------------------------------------------------------------
        migrations.AlterUniqueTogether(
            name='screeningresult',
            unique_together={('job_opening', 'source_filename')},
        ),
        migrations.RemoveField(
            model_name='screeningresult',
            name='resume',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]