# Generated by Django 6.0.5 on 2026-06-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_alter_screeningresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='status',
            field=models.CharField(choices=[('SHORTLISTED', 'Shortlisted'), ('SCHEDULED', 'Scheduled'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='SHORTLISTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='screeningresult',
            name='source_filename',
            field=models.CharField(help_text='Filename inside the configured resume directory', max_length=255),
        ),
    ]
