# Generated by Django 6.0.6 on 2026-06-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_shortlist_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Extracted via spaCy NER or filename fallback', max_length=150)),
                ('email', models.EmailField(blank=True, help_text='Extracted via Regex', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Extracted via Regex', max_length=20, null=True)),
                ('source_filename', models.CharField(help_text='Original uploaded filename', max_length=255)),
                ('resume_file', models.FileField(blank=True, help_text='Resume file saved on disk', null=True, upload_to='resumes/')),
                ('content_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 of file bytes — prevents duplicate uploads', max_length=64)),
                ('is_embedded', models.BooleanField(default=False, help_text='True once resume chunks are stored in ChromaDB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
